# Generated by Django 5.0.14 on 2026-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('cpu', models.FloatField(null=True)),
                ('ram', models.FloatField(null=True)),
                ('temp', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('-ts',),
                'indexes': [models.Index(fields=['ts'], name='fleet_metri_ts_8c3ba3_idx')],
            },
        ),
    ]
