# Generated by Django 5.0.14 on 2026-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsample',
            name='batt_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='disk_io',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='disk_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='fan_rpm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='gpu_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='iops',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='net_rx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='net_tx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metricsample',
            name='power_w',
            field=models.FloatField(null=True),
        ),
    ]
