# Generated by Django 5.0.14 on 2026-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_metricsample_batt_pct_metricsample_disk_io_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsample',
            name='power_est',
            field=models.BooleanField(default=False),
        ),
    ]
